// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ai-chat-clear-button'
  | 'ai-chat-header'
  | 'ai-chat-sidenav-tooltip'
  | 'ai-toc-header'
  | 'ai-toc-refresh-tooltip'
  | 'ai-toc-sidenav-tooltip'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'menuitem-submenulabel'
  | 'menupopup-label'
  | 'pref-api-key'
  | 'pref-chat-history'
  | 'pref-claude-title'
  | 'pref-default-provider'
  | 'pref-endpoint'
  | 'pref-generic-title'
  | 'pref-help'
  | 'pref-model'
  | 'pref-ollama-title'
  | 'pref-openai-title'
  | 'pref-title'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
